### ISSUE TITLE
AUTOREV usage by layer

### ISSUE THREAD

**Issue by roman-khimov** [madisongh/meta-golang#5]
At the moment README explicitly tells us:

```
Package dependencies are specified in recipes.  By default,
packages use AUTOREV floating revisions, but you can lock down
specific versions using SRCREV overrides for packages you include
in your build.
```

But in my opinion that's questionable practice. There is an obvious positive side of AUTOREV in that you're free from manual SRCREV bumps whenever something updates, and that also matches the default behaviour of `go get`, but this default leads to build instability, which is very dangerous. IMO any real build will need to pick some particular SRCREVs (to be stable), and telling everyone that you need to pick one makes using this layer a bit harder (and again dangerous, as it's easy to miss some packages).

Also, this makes layer itself unstable, because packages do change and may introduce new dependencies or changes that will break the recipe, so it can compile today and break tomorrow without any change in the layer.

Had these issues been considered or are there any other reasons for AUTOREV?

**Comment by madisongh** [comment]
Yes, the underlying philosophy behind go's handling of packages is pretty much diametrically opposed to the traditional well-defined-release approach that I was used to.  I didn't want to lock in a specific policy until I (and hopefully others) had some experience to share regarding the tradeoff between the go-style and OE-style approaches.

Also, since maintaining this layer has so far been a one-man operation conducted in my spare time and on my own dime, I haven't really had the resources at my disposal to do what I think would be needed in terms of automating the SRCREV updates and testing the various package combinations - much as I'd like to.

I do periodically run some test builds and fix up dependencies when they change, but more is certainly needed.  

Certainly for releasing a product, one needs to have the SRCREVs locked down, and I have done that in my production distros.  I have experimented with different combinations of floating and locking SRCREVs for go packages during development cycles as well, so it may be time to formulate a policy for the layer and put it in place.

I think, though, that if I do end up locking most of the recipes' SRCREVs, that I'll be forced to start pruning out most of the recipes currently in the layer, getting it down to a very small core set of packages, so it's something maintainable on the small scale I can afford.

I'd welcome any suggestions on this front, particularly from folks that are actively using the layer.

**Comment by madisongh** [comment]
As I have wrestled with several floating srcrev issues over the last week or so, I have gone ahead and implemented the policy outlined above, starting with the morty release branch and going forward:
- Reduced the number of recipes to a core set
- Set fixed SRCREV settings on the release branch

The master branch will continue to use AUTOREV, at least for now.

**Comment by ernstp** [comment]
Yes this was good, today golang-mqtt-paho_git.bb
gives Connection reset by peer from GO_SRCROOT = "git.eclipse.org/gitroot/paho/org.eclipse.paho.mqtt.golang.git"
on Krogoth.
